// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "38207c3586161f8d509733b27cb4597c"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"219f70cdf30f6f12b6c726d0cb3c36b8": "1f8b08000000000000ff2c8d3f6bc33014c4777d8a0323b007c97b4833a5a593a76ea510113d5ba28a5e909ee960fadd83ff4c07c7ef7ed7e093d2934a55ca18a306163ae12bc48a312642ac70b3b09928537142dee2ca1858f0eea36c1375d66f18b9a00d1d6246d87d58a02faa69f07d5b816007f720e8cbeda70d22cf7aeafb893ddf2d97a9df898f39a583ea366b1cd1067be57b87a590cc25e3e1caafe7bf7cf4ffebc95963cb57000000ffff327f9dc2cc000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("github.com/gobuffalo/helpers/genny/docs/templates", "../docs/templates")
		b.SetResolver("README.md.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "219f70cdf30f6f12b6c726d0cb3c36b8"})
	}()

	return nil
}()
